# Phyton Temelleri Tekrar


Kullanıcıdan veri getirme

In [ ]:
kullanici_veri=input("Yaşinizi giriniz")
print(type(kullanici_veri)) # öğrenmiş olduk ki input her zaman string geliyor.


Yaşinizi giriniz24
<class 'str'>


In [ ]:
#phyton string ile integear toplanmasına izin vermez!
#son_veri=kullanici_veri+10
#print(son_veri)  hata almaması için yorum satırı koydum


Veri Dönüştürme


In [ ]:
donusturulen_veri=int(kullanici_veri)
print(donusturulen_veri+10)


34


#**Veri Yapıları**

*List,Tuple,Set,Dictionary*



1-)*List* []




In [ ]:
#list'leri [] ile oluştururuz
arabalar=["Mercedes-G","BMW M5","Bugatti Veyron","Ferrari SF90",1] #farklı veri türü tutabiliyoruz
#ekleme-çıkarma ,güncellemelere ,tekarlı verilere izin verir. Sıralı bir şekilde tutar
print(arabalar[1]) #BMW M5
arabalar.count("Mercedes-G") #stringe EŞİT olan kaç tane değer olduğunu dönDERİR
arabalar.remove("BMW M5") #bmw m5 listeden çıkarıldı
arabalar.append("insert last as Default")
arabalar.insert(1,"insert as index no")
print(arabalar.index("Bugatti Veyron")) #bugatti veyron indexi
print(arabalar)
arabalar[1]="BMW F90"
arabalar.pop() # index vermezsek son elemanı siler
arabalar.append("Mercedes-G")#tekrarlı veri tutabilir.
print(arabalar)
arabalar[0:3:2] #0dan 3. indexe 2 arta arta git
arabalar[0:len(arabalar)+1:+1]


BMW M5
2
['Mercedes-G', 'insert as index no', 'Bugatti Veyron', 'Ferrari SF90', 1, 'insert last as Default']
['Mercedes-G', 'BMW F90', 'Bugatti Veyron', 'Ferrari SF90', 1, 'Mercedes-G']


['Mercedes-G', 'BMW F90', 'Bugatti Veyron', 'Ferrari SF90', 1, 'Mercedes-G']

2-)*Tuple* ()

In [ ]:
veritabani=("LocalHost","UserName",123456) #burada farklı veri tiplerini veri tutuyoruz
sayilar=(1,2,3,3)


print("3 sayısı kaçıncı indexte :",sayilar.index(3)) #içerisine yazdığımız veri kaçıncı indexte olduğunu döner

print("Tuple 3 değerinden kaç tane tutuyor:",sayilar.count(3))
# Tuple sonradan değiştirilemez verileri tutar yukarıdaki gibi veritabanı bilgileri olabilir
# tekrarlı veri var eleme çıkarma yok
sayilar2=(4,5,6)
tuple3=sayilar+sayilar2
print(tuple3) #yanyana yazar ilk sayılar sonra sayilar 2  diye


3 sayısı kaçıncı indexte : 2
Tuple 3 değerinden kaç tane tutuyor: 2
(1, 2, 3, 3, 4, 5, 6)


3-)*Set* {}


In [ ]:
set1={1,2,3,4,5,6,7,7,7,7,7,7,7} #tekrarlı verileri tutmaz örnek olarak liste yapıp sete dönüştürwlim
list1=[1,2,3,3,3,3,3,3]
print("set1 :   ",set1)
set2=set(list1) #tekrar edenleri tutmadı

print("Liste yapısı:   ",list1)
print("Set yapısı:  ",set2) ,

set2.add(5)
print("Set1 ve Set2 farkı:  ",set1.difference(set2)) # setler küme gibi çalışır yani biz burada set1(fark)set2 yaptık

print("Set1 ve Set2 Kesişim   :",set1.intersection(set2) )

set1.intersection_update(set2) #kesişim sonucunu set1 methodu ile günceller !set1 değişti!
print(set1)

set1.isdisjoint(set2) #Ortak eleman olmamasını kontrol eder. VARSA FALSE yoksa True döndürür.




set1 :    {1, 2, 3, 4, 5, 6, 7}
Liste yapısı:    [1, 2, 3, 3, 3, 3, 3, 3]
Set yapısı:   {1, 2, 3}
Set1 ve Set2 farkı:   {4, 6, 7}
Set1 ve Set2 Kesişim   : {1, 2, 3, 5}
{1, 2, 3, 5}


False

4-)*DICTIONARY* {key,value}


In [ ]:
kisi={
    "Name":"Recep",
    "Surname" :"Çakar",
    "Age":"21"
}


Employees={
    "Names":["Recep","Harun","Hamza"],
    "Ages":[21,14,14],
    "City":["Amsterdam","Miami","Los Angeles"]
}

print("Yaş Satırı",Employees["Ages"])

Employees["Ages"]=[21,12,12] #Güncellemeye izin verir

print("Yaş Satırı Güncellendi",Employees["Ages"])

Employees["Maas"]=[121,2131,1212] #sonradan eklenebilir.
Employees.keys
Employees.values
print(Employees.get("Maas","Bulunamadı")) #eğer key bulamazsa bulunumadaı yaz


Yaş Satırı [21, 14, 14]
Yaş Satırı Güncellendi [21, 12, 12]
[121, 2131, 1212]


#**Fonksiyonlar**

In [ ]:
def HelloMachineLearning():
  print("Hello Machine Learning")

def HelloInput(Input):
  print("Hello ",Input)

def sumfunc(a=1,b=1):#EĞER DEĞER GÖNDERMEZSEK HATA GELCEĞİNDEN DEFAULT DEĞER ATAMALIYIZ
  return a+b


HelloMachineLearning()
HelloInput("KNN ALGORITHM")
DonenDeger=sumfunc(15,23)
print(DonenDeger)


#globals().items() #tüm değişkenleri vs getirir


Hello Machine Learning
Hello  KNN ALGORITHM
38


#**CLASS**

1-)Self ve __init__ Parametreleri

In [ ]:
class Hayvan:
  pass#şimdilik bir şey yazmıcam hata verme

Hayvan1=Hayvan()
type(Hayvan1)

class Otobus:
  yolcular=[]

istanbulOtobusu=Otobus()
istanbulOtobusu.yolcular=["Ali","Ahmet","Mehmet","Zeki"]#içinde yolcu olsaydı silincekti append ile daha doğru
#fakat append kullanırsam eğer bir sonraki ankara otobüsünde de bu yolcular gözükcek önlem almalıyız =>self
# = görünce yeni bir değer oluituruyor ama direkt append dediğimizde classı baz alıyor!
AnkaraOtobusu=Otobus()
AnkaraOtobusu.yolcular=(["Kerem","Hayri","Basri"])

print(AnkaraOtobusu.yolcular)
print(istanbulOtobusu.yolcular)


print("----------------------------------")
print("----------------------------------")
print("----------------------------------")
class Otobusler: #üst classta self olmadığında herhangi bir nesnede yaptığım özellik hepsinde olmuş olucaktı
  def __init__(self,plaka):#yapıcı method
    self.yolcular=[]
    self.OtobusPlaka=plaka


cideAslan=Otobusler("34 CDE 37")

cideAslan.yolcular.append("Recep")
print(cideAslan.yolcular)
print(cideAslan.OtobusPlaka)

Tekiner=Otobusler("37 CDE 34")
Tekiner.yolcular.append("Veli")
print(Tekiner.yolcular)
print(Tekiner.OtobusPlaka)

#self ile ikisi de farkı nesneyi kullandı

print("----------------------------------")
print("----------------------------------")
print("----------------------------------")

class Araba:
  lastik=4 #her arabada aynı ama değişceği zaman = kullanılcağından dolayı sadece kendini etkiler
  #bir nevi ortak yerlerin riski tuple set ve list'lerde ortaya çıkıyor diyebiliriz
  def __init__(self,ArabaMarkasi="BMW",KM=2026):
    self.ArabaMarka=ArabaMarkasi
    self.ArabaKM=KM


BMW=Araba("BMW 5.20",10002)
BMW.lastik=2

Merco=Araba("Mercedes CL200",23422)


print(BMW.lastik)
print(Merco.lastik)

['Kerem', 'Hayri', 'Basri']
['Ali', 'Ahmet', 'Mehmet', 'Zeki']
----------------------------------
----------------------------------
----------------------------------
['Recep']
34 CDE 37
['Veli']
37 CDE 34
----------------------------------
----------------------------------
----------------------------------
2
4


2-)Class içinde funct tanımlama

In [ ]:
class GidebilenAraba:
  Elfreni="Aktif"
  def __init__(self,Hiz=1,Beygir=100,Model="Tofask"):
    self.ArabaHiz=Hiz
    self.ArabaBeygir=Beygir
    self.ArabaModel=Model

  def ArabaCalistir(self):
    print("Araba Calisti")
    GidebilenAraba.Elfreni="Pasif" #Bu hata bilerek koydum phytonda global ve local değişkenleri ve nesne farklılıklarını anlamak için
    #burada elfreni pasif yaptık globalde sonrasında oluşturulan nesne de pasif gördü


araba1=GidebilenAraba(23,122,"BMW")
araba1.ArabaCalistir()
print(araba1.Elfreni)
araba2=GidebilenAraba(22,123,"Merco")
print(araba2.Elfreni)







Araba Calisti
Pasif
Pasif


#ENCAPSULATION

In [ ]:
"""class BankaHesabi:
  def __init__(self,iban,isim):
    self.BankaIban=iban
    self.Tutar=0
    self.Name=isim

banka1=BankaHesabi("TR21231213","Recep")
banka1.Tutar=233232 # herkes erişti oldu mu bu şimdi?
"""
# c#ta private public kullanılırdı burda da aynı ama şekil farklı
# isim -> public
# _isim -> protected
# __isim -> private   --------------------method için de geçerli bunlar (__)
class BankaHesabi:
  def __init__(self,iban,isim):
    self.BankaIban=iban
    self.__Tutar=0
    self.Name=isim
  def BakiyeGoruntule(self): #getter
    print(self.__Tutar)
  def BakiyeGuncelle(self,GelenHvale):#setter
    self.__Tutar+=GelenHvale


banka1=BankaHesabi("TR21231213","Recep")
#banka1.#tutar gözükmedi çünkü private

#güzel bir soru soruldu => "Hocam zaten değiştirebiliyorduk neden uğraştık koda erişen biri ikisini de görüyor"
#kendime tekrar notu => api'lar ile biz veri gönderirken method kullanıyoruz orada fluentvalidation diagramlarını methoda ekleyebiliriz
#ama direkt erişime ekleyemeyiz !!!


#INHERITANCE

In [ ]:
class Araba:
  def __init__(self,isim):
    self.ArabaIsım=isim

class ElektrikliAraba(Araba):
  def __init__(self, isim):
    super().__init__(isim)
    #super ->base classı temsil eder

class BenzinliAraba(Araba): #inherıtance kulllanırken () yapılır.
  def __init__(self, isim):
    super().__init__(isim)



ea1=ElektrikliAraba("Tesla")
print(ea1.ArabaIsım)

ba1=BenzinliAraba("Kia")
print(ba1.ArabaIsım)

Tesla
Kia


#POLYMORPHISM

In [ ]:
class kopek:
  def ses_cikar(self):
    print("havahav")
class kedi:
  def ses_cikar(self):
    print("miyav")

class kertenkele:
  def ses_cikar(self):
    print("tısss")

k1=kopek()
ke1=kedi()
ker1=kertenkele()
k1.ses_cikar() #phytonda çağırdığımız methoda otamatik nesne gönderilir bundan dolayı eğer yukarıda self yazmazsak hata alırız
#ben senden parametre istemedim ama sen gönderiyorsun ??

ker1.ses_cikar()
ke1.ses_cikar()

#POLYMORPHISM bir fonksiyon adının farklı classlarda farkı işi sergilemesi


havahav
tısss
miyav


#ABSTRACTION

Bir araba markası yeni bir araba modeli geliştirecektir.
Arabada bulunması gereken temel bileşenler (gaz pedalı, fren, gösterge paneli vb.) önceden bellidir.
Bu ortak yapı ve davranışları her araba türünde tekrar yazmak yerine abstract (ABC) bir üst sınıfta tanımlarız.
**Abstract class’tan nesne oluşturulamaz**; **`sadece alt sınıflar için bir şablon (sözleşme) görevi görür.`**
Elektrikli veya benzinli arabalar bu üst sınıftan türetilir ve zorunlu metotları kendi mantıklarına göre uygular.

In [ ]:
from abc import ABC,abstractmethod #abstract kullanmak için gerekli olan kütüphanemiz

class Arac(ABC): #Abstract classtan türedi yani soyut oldu
  @abstractmethod
  def gitmek(self):# eğer başına @abstractmethod yazmazsak miras alan classlara zorunlu olmaz
    print("arac gider")
  @abstractmethod
  def istopEtmek(self):
    print("arac istop eder")

class lpgArac(Arac):
  def __init__(self):
    self.LPG=0
  def gitmek(self):
    return super().gitmek()
  def istopEtmek(self):
    print("ya da istersek başka bi şey döndeririz")
#lpgArac1=lpgArac() # nesne oluşturmaz çünkü abc methodları alt clasta oluşturmadın der
lpgArac1=lpgArac()
lpgArac1.gitmek()
lpgArac1.istopEtmek()


arac gider
ya da istersek başka bi şey döndeririz


#NUMPY
Numpy bilimsel hesaplamaları yapmamızda yardımcı olur

In [ ]:
import numpy as np
list1=[1,2,3,4,5]
array1=np.array([[1,2,3,4,5],[1,2,3,4,5]]) #2 boyutlu liste alır !!!
#print(array1)
#print(list1)
#array listelerden hızlıdr!! array sıralı liste ise dağınık tutar o yüzden

vektor1=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
matris1=vektor1.reshape(3,4) #3 satır 4 sütun şeklinde ayır
#print(matris1)#çarpı 2 falan desem her elemanı tek tek arpar toplar...

#print(matris1.ndim) #kaç boyutlu matris?
#print(matris1.shape) #kaçlık matris olduğunu söyler
#print(matris1.dtype) #matristeki veri türleri
#print(matris1.size)  #kaç tane veri var row*column


#özel matris yaratmak isteyebiliriz.
#0 matrisi
zero_matris=np.zeros((2,2)) #
#print(zero_matris) #

#random matris

random_matris=np.random.rand(3,2) #0 ile 1 arasında değer veriyor!!!!!
#print(random_matris)

#random belli değer aralığında matris

lin_matris=np.linspace(0,10,5) # 0-10 arasında eşit uzaklıkta 5 parça
#lin_matris


#transpoze alma

transpozematris1=matris1.T
print(transpozematris1)
print("-------------------------------------------")
print("matris min : ",matris1.min())
print("Matris max: ",matris1.max ())
print("Matris mean: ",matris1.mean())
print("Matris sum: ",matris1.sum())

matris1[0,0] #0.elaman
matris1[2:3] # 2.satırı komple getirir
matris1[2:3,0:2] #2. satırda 1. ve 2.  elemeanı getirir




ravel_matris=matris1.ravel() #matrisi vektöre çevirir
print("Ravel ile vektöre çevrilmiş matris: ",ravel_matris)

print("-------------------------------------------")
print("-------------------------------------------")


#VEKTOR BİRLŞETİRME

Vector1=np.array([1,2])
Vector2=np.array([3,4])


#yatayda birleştirme
YatayBirlesme=np.hstack((Vector1,Vector2)) #tuple da göndersem oluyor list de
print("Hstack ile Yatay Birleşme :",YatayBirlesme)


#dikey birleştirme
DikeyBirlesme=np.vstack((Vector1,Vector2))
print("Vstack ile Dikey Birleşme : \n ",DikeyBirlesme)


print("-------------------------------------------")
print("-------------------------------------------")




#not matris2=matris 1 yaptığımızda matris2 de değer değişince 1de de değişir!
#bunun önüne geçmek için matris1.copy() yapmalıyız

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
-------------------------------------------
matris min :  1
Matris max:  12
Matris mean:  6.5
Matris sum:  78
Ravel ile vektöre çevrilmiş matris:  [ 1  2  3  4  5  6  7  8  9 10 11 12]
-------------------------------------------
-------------------------------------------
Yatay Birleşme : [[1 2]
 [3 4]]
Dikey Birleme : 
  [[1 3]
 [2 4]]
-------------------------------------------
-------------------------------------------


/tmp/ipython-input-1410549083.py:66: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  YatayBirlesme=np.row_stack((Vector1,Vector2)) #tuple da göndersem oluyor list de


#PANDAS

In [ ]:
import pandas as pd

list1=[1,2,3,4,5,6]
series1=pd.Series(list1)

series1[-1]=23 #sona ekler ama indexi -1 yapar length değil !!!
list1[-1]=23 #sona ekler

print("list :",list1)
print ("Series: ",series1)

dic1={
    "AdAsKey":["Azure","Amazon","Microsoft"],
    "YearAsKey":[2002,2000,1990]
    }

df=pd.DataFrame(dic1)
print(df) #like table

df.loc[0] # ilk satırı getirir.
#df.loc[-1] #son elemanıgetirmez series gibi çalışıyor !!!!
df.loc[df["AdAsKey"]=="Azure"]
df.head()
df.tail()
df.columns
df.dtypes
df.loc[-1]={
    "AdAsKey":"Lenovo",
    "YearAsKey":2012
}
print(df)
df.drop(-1,axis=0,inplace=True)# kaldırır inplace true yapmazsak güncellemez mesela ileride yeni değiştirilcek değeri kullanırken
# koşul sağlanmazsa veritabanını değiştirme demek için
#axis=0 satır siler
#axis=1 sütun siler

df["YearAsKey"].max()



list : [1, 2, 3, 4, 5, 23]
Series:   0     1
 1     2
 2     3
 3     4
 4     5
 5     6
-1    23
dtype: int64
     AdAsKey  YearAsKey
0      Azure       2002
1     Amazon       2000
2  Microsoft       1990
      AdAsKey  YearAsKey
 0      Azure       2002
 1     Amazon       2000
 2  Microsoft       1990
-1     Lenovo       2012


2012